version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: husky
    versions:
    - ">=5.0.0"
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: npm
  directory: "/packages/contentful-extension-scripts"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: htmlnano
    versions:
    - 0.2.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: jest-watch-typeahead
    versions:
    - 0.6.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: npm
  directory: "/packages/create-contentful-extension"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: npm
  directory: "/packages/eslint-config-extension"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.4
    - 24.1.5
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: semver
    versions:
    - 7.3.4
  registries:
  - npm-registry-registry-npmjs-org
